In [1]:
# %% 
import time, os, json
from pathlib import Path
import pandas as pd
import numpy as np
import itertools
from tqdm.notebook import tqdm
from tqdm_joblib import tqdm_joblib
from sklearn.model_selection import ParameterSampler

from FIT_python.pipeline_individual_id.pairwise_individual_id_pipeline import (
    run_all_pairwise_projections_parallel
)
from FIT_python.pipeline_individual_id.generate_trails_and_trailpairs import (
    generate_pairwise_comparisons_from_df
)

# %% 1) Basis-Pfade & Hyperparameter-Räume
splits_root = Path("C:/Users/Frede/OneDrive/Projects and Disschaptors/FIT_package/data/splits")
models_root = Path(r"C:\Users\Frede\OneDrive\Projects and Disschaptors\FIT_package\results\data\random_search_standard_metrics\best_maj_test_pct")
output_root = Path("C:/Users/Frede/OneDrive/Projects and Disschaptors/FIT_package/results/data/pairwise_comp_all_species_experiment")
output_root.mkdir(parents=True, exist_ok=True)

feature_counts    = [2,5,10,15,50,20,50,100,200]
selection_methods = ["random_forest","forward","univariate","variance","lasso"]
reducers          = ["pca","lda","umap"]
n_components_list = [2, 3, 5, 10]
outlier_methods   = [None,"clip","zscore"]
scaler_methods    = [None,"standard","robust"]
use_sex_opts      = [False, True]
n_jobs            = -1

# %% 2) Grid erzeugen & 100 auswählen
grid = pd.DataFrame(
    itertools.product(
        feature_counts,
        selection_methods,
        reducers,
        n_components_list,
        outlier_methods,
        scaler_methods,
        use_sex_opts
    ),
    columns=[
        "feature_count",
        "selection_method",
        "reducer",
        "n_components",
        "outlier_method",
        "scaler_method",
        "use_sex"
    ]
).sort_values("feature_count", ascending=False).reset_index(drop=True)

sampled_grid = grid.sample(n=40, random_state=42)
sampled_grid = sampled_grid.sort_values("feature_count", ascending=False).reset_index(drop=True)

# === Zusätzliche Standard-Methoden einfügen ===
std_feature_counts   = [10, 12, 14, 16, 18, 20]
std_selection_method = "forward"
std_reducer          = "lda"
std_n_components     = 2     # bei LDA nicht relevant
std_outlier_method   = None
std_scaler_method    = None

extra = []
for fc in std_feature_counts:
    for use_sex in [False, True]:
        extra.append({
            "feature_count":    fc,
            "selection_method": std_selection_method,
            "reducer":          std_reducer,
            "n_components":     std_n_components,
            "outlier_method":   std_outlier_method,
            "scaler_method":    std_scaler_method,
            "use_sex":          use_sex
        })

extra_df = pd.DataFrame(extra)

# an sampled_grid anhängen und wieder sortieren
sampled_grid = pd.concat([sampled_grid, extra_df], ignore_index=True)
sampled_grid = sampled_grid.sort_values("feature_count", ascending=False).reset_index(drop=True)

# %% 3) Spezies-Schleife
for species_dir in sorted(splits_root.iterdir()):
    if not species_dir.is_dir(): 
        continue
    species = species_dir.name
    print(f"\n🔄 Processing species: {species}")

    # 3.1) Daten laden
    df = pd.read_csv(species_dir / "train.csv")

    # 3.2) Feature-Spalten wählen
    if species == "eurasian_otter_(1)":
        feature_cols = [
            c for c in df.columns 
            if c.startswith(("dist","ang","t")) and pd.api.types.is_numeric_dtype(df[c])
        ]
    else:
        feature_cols = [
            c for c in df.columns[5:]
            if pd.api.types.is_numeric_dtype(df[c])
        ]
    print(f"  → {len(feature_cols)} numerische Features")

    # 3.3) Pairs & Summary generieren
    comps, summary = generate_pairwise_comparisons_from_df(
        df,
        id_col="individual_id",
        chunk_size=10,
        trail_size_list=[9,7,5,3,2],
        max_individuals=20,
        max_trails_per_animal=2,
        n_folds=3,
        random_state=42
    )
    print("  Summary der Trail-Längen:")
    display(summary)

    # 3.4) Resume-Logik für species-spezifisches Parquet
    results_fp = output_root / f"{species}_all_results_combined.parquet"
    if results_fp.exists():
        done = pd.read_parquet(results_fp, columns=sampled_grid.columns)
        done_keys = set(tuple(r) for r in done.values)
        todo = sampled_grid[
            sampled_grid.apply(lambda row: tuple(row.values) not in done_keys, axis=1)
        ].reset_index(drop=True)
    else:
        todo = sampled_grid.copy()

    print(f"  → Noch offen: {len(todo)}/{len(sampled_grid)} Runs")

    # 3.5) Hyper-Parameter-Loop
    for idx, row in todo.iterrows():
        fc, sel, red, nc, out, scl, sex = (
            int(row.feature_count),
            row.selection_method,
            row.reducer,
            int(row.n_components),
            row.outlier_method,
            row.scaler_method,
            bool(row.use_sex)
        )
        desc = (
            f"FC={fc}|FS={sel}|Red={red}/{nc}|Out={out}|Scl={scl}|Sex={'on' if sex else 'off'}"
        )
        print(f"    → Run {idx+1}/{len(todo)}: {desc}")
        t0 = time.time()

        # gewrappt in Listen:
        out_list = [out] if out is not None else [None]
        scl_list = [scl] if scl is not None else [None]

        with tqdm_joblib(tqdm(desc=desc, total=len(comps), leave=False)):
            res = run_all_pairwise_projections_parallel(
                comparisons=comps,
                df=df,
                feature_cols=feature_cols,
                k_features=fc,
                selection_method=sel,
                reducers=[red],           # bleibt wie gehabt
                n_components=[nc],        # bleibt wie gehabt
                outlier_methods=out_list, # **jetzt eine Liste**
                scaler_methods=scl_list,  # **jetzt eine Liste**
                use_sexmodel_prediction=sex,
                sexmodel_path=(
                    models_root / f"{species}.joblib"
                    if sex else None
                ),
                debug=False,
                n_jobs=n_jobs
            )
        print(f"      → {len(res)} Rows in {time.time()-t0:.1f}s")

        # 3.6) Results anreichern & speichern
        df_run = pd.DataFrame(res)
        for col in sampled_grid.columns:
            df_run[col] = row[col]
        if results_fp.exists():
            df_full = pd.concat([pd.read_parquet(results_fp), df_run], ignore_index=True)
        else:
            df_full = df_run
        df_full.to_parquet(results_fp, index=False)

    print(f"  ✅ Fertig für {species}, Parquet: {results_fp}")

# %% 4) Alle Spezies vereinen
all_parquets = list(output_root.glob("*_all_results_combined.parquet"))
df_all = pd.concat((pd.read_parquet(p) for p in all_parquets), ignore_index=True)
df_all.to_parquet(output_root / "all_species_all_results_combined.parquet", index=False)
print("\n🎉 Fertig – Gesamt-Parquet erzeugt:")
print(f"   {output_root/'all_species_all_results_combined.parquet'}")
display(df_all.head())

      → 1279 Rows in 80.9s
    → Run 38/40: FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on

FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/1279 [00:00<?, ?it/s]

  0%|          | 0/1279 [00:00<?, ?it/s]

  0%|          | 0/1279 [00:00<?, ?it/s]

      → 1279 Rows in 2.3s
    → Run 39/40: FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off

FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off:   0%|          | 0/1279 [00:00<?, ?it/s]

  0%|          | 0/1279 [00:00<?, ?it/s]

  0%|          | 0/1279 [00:00<?, ?it/s]

      → 1279 Rows in 96.1s
    → Run 40/40: FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on

FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on:   0%|          | 0/1279 [00:00<?, ?it/s]

  0%|          | 0/1279 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/1279 [03:53<?, ?it/s]
Processing Pairs:   0%|          | 0/1279 [03:25<?, ?it/s]
Processing Pairs:   0%|          | 0/1279 [03:10<?, ?it/s]
Processing Pairs:   0%|          | 0/1279 [01:45<?, ?it/s]
Processing Pairs:   0%|          | 0/1279 [01:39<?, ?it/s]
Processing Pairs:   0%|          | 0/1279 [00:00<?, ?it/s]

  0%|          | 0/1279 [00:00<?, ?it/s]

      → 1279 Rows in 5.5s
  ✅ Fertig für giant_panda, Parquet: C:\Users\Frede\OneDrive\Projects and Disschaptors\FIT_package\results\data\pairwise_comp_all_species_experiment\giant_panda_all_results_combined.parquet

🔄 Processing species: jubatus
  → 137 numerische Features
  Summary der Trail-Längen:

,sub_size,n_animals,n_trails,avg_comp_per_ind_same,sd_comp_per_ind_same,avg_comp_per_ind_diff,sd_comp_per_ind_diff,ratio_same_to_diff
0,9,20,20,NaN,NaN,NaN,NaN,NaN
1,7,20,20,NaN,NaN,NaN,NaN,NaN
2,5,20,20,NaN,NaN,NaN,NaN,NaN
3,3,20,40,NaN,NaN,NaN,NaN,NaN
4,2,20,40,NaN,NaN,NaN,NaN,NaN
5,Total,20,2290,10.0,0.0,209.0,0.0,0.095694

  → Noch offen: 40/52 Runs
    → Run 1/40: FC=200|FS=variance|Red=umap/3|Out=clip|Scl=standard|Sex=on

FC=200|FS=variance|Red=umap/3|Out=clip|Scl=standard|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 110.0s
    → Run 2/40: FC=200|FS=univariate|Red=pca/5|Out=None|Scl=robust|Sex=on

FC=200|FS=univariate|Red=pca/5|Out=None|Scl=robust|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 6.4s
    → Run 3/40: FC=200|FS=univariate|Red=pca/10|Out=clip|Scl=robust|Sex=off

FC=200|FS=univariate|Red=pca/10|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/1279 [02:08<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [01:59<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:09<?, ?it/s]

      → 2290 Rows in 6.5s
    → Run 4/40: FC=100|FS=forward|Red=lda/2|Out=None|Scl=None|Sex=off

FC=100|FS=forward|Red=lda/2|Out=None|Scl=None|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 1093.1s
    → Run 5/40: FC=100|FS=lasso|Red=lda/5|Out=zscore|Scl=standard|Sex=on

FC=100|FS=lasso|Red=lda/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 41.0s
    → Run 6/40: FC=100|FS=univariate|Red=pca/10|Out=zscore|Scl=robust|Sex=off

FC=100|FS=univariate|Red=pca/10|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [19:06<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [18:58<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:44<?, ?it/s]

      → 2290 Rows in 4.7s
    → Run 7/40: FC=100|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off

FC=100|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 1207.5s
    → Run 8/40: FC=100|FS=univariate|Red=umap/3|Out=zscore|Scl=None|Sex=on

FC=100|FS=univariate|Red=umap/3|Out=zscore|Scl=None|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 112.0s
    → Run 9/40: FC=50|FS=univariate|Red=umap/3|Out=None|Scl=None|Sex=off

FC=50|FS=univariate|Red=umap/3|Out=None|Scl=None|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [23:11<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [23:05<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [02:56<?, ?it/s]

      → 2290 Rows in 112.6s
    → Run 10/40: FC=50|FS=random_forest|Red=lda/3|Out=zscore|Scl=robust|Sex=off

FC=50|FS=random_forest|Red=lda/3|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 23.0s
    → Run 11/40: FC=50|FS=univariate|Red=lda/3|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=lda/3|Out=clip|Scl=None|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 5.8s
    → Run 12/40: FC=50|FS=univariate|Red=pca/5|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=pca/5|Out=clip|Scl=None|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [02:31<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:36<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:11<?, ?it/s]

      → 2290 Rows in 3.8s
    → Run 13/40: FC=50|FS=variance|Red=umap/10|Out=clip|Scl=robust|Sex=on

FC=50|FS=variance|Red=umap/10|Out=clip|Scl=robust|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 146.6s
    → Run 14/40: FC=50|FS=univariate|Red=umap/5|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=umap/5|Out=clip|Scl=None|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 121.5s
    → Run 15/40: FC=50|FS=variance|Red=lda/5|Out=zscore|Scl=None|Sex=on

FC=50|FS=variance|Red=lda/5|Out=zscore|Scl=None|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 3.7s
    → Run 16/40: FC=50|FS=variance|Red=umap/5|Out=zscore|Scl=None|Sex=on

FC=50|FS=variance|Red=umap/5|Out=zscore|Scl=None|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [04:47<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [04:40<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [02:11<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:07<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 130.4s
    → Run 17/40: FC=50|FS=variance|Red=lda/3|Out=None|Scl=robust|Sex=off

FC=50|FS=variance|Red=lda/3|Out=None|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 4.8s
    → Run 18/40: FC=50|FS=lasso|Red=lda/10|Out=clip|Scl=robust|Sex=off

FC=50|FS=lasso|Red=lda/10|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 39.7s
    → Run 19/40: FC=20|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off

FC=20|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [03:11<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:58<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:50<?, ?it/s]

      → 2290 Rows in 225.9s
    → Run 20/40: FC=20|FS=univariate|Red=lda/5|Out=clip|Scl=robust|Sex=off

FC=20|FS=univariate|Red=lda/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 4.7s
    → Run 21/40: FC=20|FS=lasso|Red=pca/3|Out=zscore|Scl=None|Sex=off

FC=20|FS=lasso|Red=pca/3|Out=zscore|Scl=None|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 38.4s
    → Run 22/40: FC=20|FS=random_forest|Red=umap/2|Out=clip|Scl=None|Sex=off

FC=20|FS=random_forest|Red=umap/2|Out=clip|Scl=None|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [05:19<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [01:29<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [01:20<?, ?it/s]

      → 2290 Rows in 126.0s
    → Run 23/40: FC=20|FS=variance|Red=umap/10|Out=zscore|Scl=None|Sex=off

FC=20|FS=variance|Red=umap/10|Out=zscore|Scl=None|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 139.1s
    → Run 24/40: FC=15|FS=forward|Red=umap/5|Out=None|Scl=standard|Sex=on

FC=15|FS=forward|Red=umap/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 198.5s
    → Run 25/40: FC=15|FS=variance|Red=umap/3|Out=zscore|Scl=robust|Sex=off

FC=15|FS=variance|Red=umap/3|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [09:12<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [07:01<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [04:37<?, ?it/s]

      → 2290 Rows in 112.7s
    → Run 26/40: FC=15|FS=forward|Red=lda/10|Out=clip|Scl=standard|Sex=off

FC=15|FS=forward|Red=lda/10|Out=clip|Scl=standard|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 75.1s
    → Run 27/40: FC=15|FS=lasso|Red=pca/10|Out=zscore|Scl=robust|Sex=off

FC=15|FS=lasso|Red=pca/10|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 40.4s
    → Run 28/40: FC=15|FS=random_forest|Red=pca/2|Out=clip|Scl=robust|Sex=on

FC=15|FS=random_forest|Red=pca/2|Out=clip|Scl=robust|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 23.4s
    → Run 29/40: FC=10|FS=variance|Red=pca/2|Out=None|Scl=standard|Sex=on

FC=10|FS=variance|Red=pca/2|Out=None|Scl=standard|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [04:32<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [02:34<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [01:14<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:28<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 3.9s
    → Run 30/40: FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=on

FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 3.2s
    → Run 31/40: FC=10|FS=random_forest|Red=lda/10|Out=None|Scl=robust|Sex=on

FC=10|FS=random_forest|Red=lda/10|Out=None|Scl=robust|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 23.3s
    → Run 32/40: FC=10|FS=variance|Red=umap/5|Out=clip|Scl=robust|Sex=on

FC=10|FS=variance|Red=umap/5|Out=clip|Scl=robust|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [00:47<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:37<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:28<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 130.9s
    → Run 33/40: FC=10|FS=univariate|Red=umap/5|Out=None|Scl=standard|Sex=on

FC=10|FS=univariate|Red=umap/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 131.6s
    → Run 34/40: FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=off

FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 3.3s
    → Run 35/40: FC=10|FS=forward|Red=lda/3|Out=None|Scl=standard|Sex=off

FC=10|FS=forward|Red=lda/3|Out=None|Scl=standard|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [04:49<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [02:32<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:15<?, ?it/s]

      → 2290 Rows in 49.5s
    → Run 36/40: FC=5|FS=random_forest|Red=lda/2|Out=clip|Scl=None|Sex=on

FC=5|FS=random_forest|Red=lda/2|Out=clip|Scl=None|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 22.2s
    → Run 37/40: FC=5|FS=lasso|Red=umap/5|Out=zscore|Scl=standard|Sex=on

FC=5|FS=lasso|Red=umap/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 165.9s
    → Run 38/40: FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on

FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [04:15<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [03:20<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [02:53<?, ?it/s]

      → 2290 Rows in 3.5s
    → Run 39/40: FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off

FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 160.7s
    → Run 40/40: FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on

FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on:   0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

  0%|          | 0/2290 [00:00<?, ?it/s]

      → 2290 Rows in 13.4s
  ✅ Fertig für jubatus, Parquet: C:\Users\Frede\OneDrive\Projects and Disschaptors\FIT_package\results\data\pairwise_comp_all_species_experiment\jubatus_all_results_combined.parquet

🔄 Processing species: lowlandtapir
  → 122 numerische Features
  Summary der Trail-Längen:

,sub_size,n_animals,n_trails,avg_comp_per_ind_same,sd_comp_per_ind_same,avg_comp_per_ind_diff,sd_comp_per_ind_diff,ratio_same_to_diff
0,9,15,16,NaN,NaN,NaN,NaN,NaN
1,7,19,20,NaN,NaN,NaN,NaN,NaN
2,5,20,25,NaN,NaN,NaN,NaN,NaN
3,3,20,26,NaN,NaN,NaN,NaN,NaN
4,2,20,27,NaN,NaN,NaN,NaN,NaN
5,Total,20,1366,5.0,7.779866,126.6,38.037931,0.078989

  → Noch offen: 40/52 Runs
    → Run 1/40: FC=200|FS=variance|Red=umap/3|Out=clip|Scl=standard|Sex=on

FC=200|FS=variance|Red=umap/3|Out=clip|Scl=standard|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2290 [03:48<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [03:39<?, ?it/s]
Processing Pairs:   0%|          | 0/2290 [00:50<?, ?it/s]

      → 1366 Rows in 50.8s
    → Run 2/40: FC=200|FS=univariate|Red=pca/5|Out=None|Scl=robust|Sex=on

FC=200|FS=univariate|Red=pca/5|Out=None|Scl=robust|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 3.9s
    → Run 3/40: FC=200|FS=univariate|Red=pca/10|Out=clip|Scl=robust|Sex=off

FC=200|FS=univariate|Red=pca/10|Out=clip|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 3.6s
    → Run 4/40: FC=100|FS=forward|Red=lda/2|Out=None|Scl=None|Sex=off

FC=100|FS=forward|Red=lda/2|Out=None|Scl=None|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 506.5s
    → Run 5/40: FC=100|FS=lasso|Red=lda/5|Out=zscore|Scl=standard|Sex=on

FC=100|FS=lasso|Red=lda/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 20.3s
    → Run 6/40: FC=100|FS=univariate|Red=pca/10|Out=zscore|Scl=robust|Sex=off

FC=100|FS=univariate|Red=pca/10|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 3.6s
    → Run 7/40: FC=100|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off

FC=100|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/1366 [09:52<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [09:01<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [08:56<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [08:52<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:25<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:04<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 563.2s
    → Run 8/40: FC=100|FS=univariate|Red=umap/3|Out=zscore|Scl=None|Sex=on

FC=100|FS=univariate|Red=umap/3|Out=zscore|Scl=None|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 46.0s
    → Run 9/40: FC=50|FS=univariate|Red=umap/3|Out=None|Scl=None|Sex=off

FC=50|FS=univariate|Red=umap/3|Out=None|Scl=None|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 50.3s
    → Run 10/40: FC=50|FS=random_forest|Red=lda/3|Out=zscore|Scl=robust|Sex=off

FC=50|FS=random_forest|Red=lda/3|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 14.3s
    → Run 11/40: FC=50|FS=univariate|Red=lda/3|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=lda/3|Out=clip|Scl=None|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/1366 [11:20<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [01:56<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [01:10<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:18<?, ?it/s]

      → 1366 Rows in 3.9s
    → Run 12/40: FC=50|FS=univariate|Red=pca/5|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=pca/5|Out=clip|Scl=None|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 2.2s
    → Run 13/40: FC=50|FS=variance|Red=umap/10|Out=clip|Scl=robust|Sex=on

FC=50|FS=variance|Red=umap/10|Out=clip|Scl=robust|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 58.5s
    → Run 14/40: FC=50|FS=univariate|Red=umap/5|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=umap/5|Out=clip|Scl=None|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 54.6s
    → Run 15/40: FC=50|FS=variance|Red=lda/5|Out=zscore|Scl=None|Sex=on

FC=50|FS=variance|Red=lda/5|Out=zscore|Scl=None|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 2.2s
    → Run 16/40: FC=50|FS=variance|Red=umap/5|Out=zscore|Scl=None|Sex=on

FC=50|FS=variance|Red=umap/5|Out=zscore|Scl=None|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 53.0s

Processing Pairs:   0%|          | 0/1366 [03:02<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [02:57<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [02:53<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [01:53<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:57<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:53<?, ?it/s]

    → Run 17/40: FC=50|FS=variance|Red=lda/3|Out=None|Scl=robust|Sex=off

FC=50|FS=variance|Red=lda/3|Out=None|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 2.9s
    → Run 18/40: FC=50|FS=lasso|Red=lda/10|Out=clip|Scl=robust|Sex=off

FC=50|FS=lasso|Red=lda/10|Out=clip|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 19.6s
    → Run 19/40: FC=20|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off

FC=20|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 106.6s
    → Run 20/40: FC=20|FS=univariate|Red=lda/5|Out=clip|Scl=robust|Sex=off

FC=20|FS=univariate|Red=lda/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 3.1s
    → Run 21/40: FC=20|FS=lasso|Red=pca/3|Out=zscore|Scl=None|Sex=off

FC=20|FS=lasso|Red=pca/3|Out=zscore|Scl=None|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 18.9s

Processing Pairs:   0%|          | 0/1366 [02:40<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [02:35<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [02:14<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:25<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:20<?, ?it/s]

    → Run 22/40: FC=20|FS=random_forest|Red=umap/2|Out=clip|Scl=None|Sex=off

FC=20|FS=random_forest|Red=umap/2|Out=clip|Scl=None|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 58.0s
    → Run 23/40: FC=20|FS=variance|Red=umap/10|Out=zscore|Scl=None|Sex=off

FC=20|FS=variance|Red=umap/10|Out=zscore|Scl=None|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 61.3s
    → Run 24/40: FC=15|FS=forward|Red=umap/5|Out=None|Scl=standard|Sex=on

FC=15|FS=forward|Red=umap/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 86.8s
    → Run 25/40: FC=15|FS=variance|Red=umap/3|Out=zscore|Scl=robust|Sex=off

FC=15|FS=variance|Red=umap/3|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 48.0s
    → Run 26/40: FC=15|FS=forward|Red=lda/10|Out=clip|Scl=standard|Sex=off

FC=15|FS=forward|Red=lda/10|Out=clip|Scl=standard|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 38.1s
    → Run 27/40: FC=15|FS=lasso|Red=pca/10|Out=zscore|Scl=robust|Sex=off

FC=15|FS=lasso|Red=pca/10|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/1366 [05:04<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [04:04<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [03:00<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [01:31<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:40<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 19.8s
    → Run 28/40: FC=15|FS=random_forest|Red=pca/2|Out=clip|Scl=robust|Sex=on

FC=15|FS=random_forest|Red=pca/2|Out=clip|Scl=robust|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 14.6s
    → Run 29/40: FC=10|FS=variance|Red=pca/2|Out=None|Scl=standard|Sex=on

FC=10|FS=variance|Red=pca/2|Out=None|Scl=standard|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 2.3s
    → Run 30/40: FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=on

FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 2.3s
    → Run 31/40: FC=10|FS=random_forest|Red=lda/10|Out=None|Scl=robust|Sex=on

FC=10|FS=random_forest|Red=lda/10|Out=None|Scl=robust|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 14.8s
    → Run 32/40: FC=10|FS=variance|Red=umap/5|Out=clip|Scl=robust|Sex=on

FC=10|FS=variance|Red=umap/5|Out=clip|Scl=robust|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/1366 [01:07<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:45<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:27<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:22<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:17<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 50.7s
    → Run 33/40: FC=10|FS=univariate|Red=umap/5|Out=None|Scl=standard|Sex=on

FC=10|FS=univariate|Red=umap/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 51.5s
    → Run 34/40: FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=off

FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 2.7s
    → Run 35/40: FC=10|FS=forward|Red=lda/3|Out=None|Scl=standard|Sex=off

FC=10|FS=forward|Red=lda/3|Out=None|Scl=standard|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 21.2s
    → Run 36/40: FC=5|FS=random_forest|Red=lda/2|Out=clip|Scl=None|Sex=on

FC=5|FS=random_forest|Red=lda/2|Out=clip|Scl=None|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 13.4s
    → Run 37/40: FC=5|FS=lasso|Red=umap/5|Out=zscore|Scl=standard|Sex=on

FC=5|FS=lasso|Red=umap/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/1366 [02:35<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [01:41<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:46<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:41<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:16<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 70.4s
    → Run 38/40: FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on

FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 2.1s
    → Run 39/40: FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off

FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 69.7s
    → Run 40/40: FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on

FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on:   0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

  0%|          | 0/1366 [00:00<?, ?it/s]

      → 1366 Rows in 7.4s
  ✅ Fertig für lowlandtapir, Parquet: C:\Users\Frede\OneDrive\Projects and Disschaptors\FIT_package\results\data\pairwise_comp_all_species_experiment\lowlandtapir_all_results_combined.parquet

🔄 Processing species: mountain_lion
  → 134 numerische Features
  Summary der Trail-Längen:

,sub_size,n_animals,n_trails,avg_comp_per_ind_same,sd_comp_per_ind_same,avg_comp_per_ind_diff,sd_comp_per_ind_diff,ratio_same_to_diff
0,9,17,23,NaN,NaN,NaN,NaN,NaN
1,7,18,26,NaN,NaN,NaN,NaN,NaN
2,5,20,31,NaN,NaN,NaN,NaN,NaN
3,3,20,34,NaN,NaN,NaN,NaN,NaN
4,2,20,36,NaN,NaN,NaN,NaN,NaN
5,Total,20,2454,13.75,9.716373,217.9,62.522333,0.126205

  → Noch offen: 40/52 Runs
    → Run 1/40: FC=200|FS=variance|Red=umap/3|Out=clip|Scl=standard|Sex=on

FC=200|FS=variance|Red=umap/3|Out=clip|Scl=standard|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/1366 [03:54<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [02:41<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [02:35<?, ?it/s]
Processing Pairs:   0%|          | 0/1366 [01:22<?, ?it/s]

      → 2454 Rows in 121.7s
    → Run 2/40: FC=200|FS=univariate|Red=pca/5|Out=None|Scl=robust|Sex=on

FC=200|FS=univariate|Red=pca/5|Out=None|Scl=robust|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 7.5s
    → Run 3/40: FC=200|FS=univariate|Red=pca/10|Out=clip|Scl=robust|Sex=off

FC=200|FS=univariate|Red=pca/10|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 7.1s
    → Run 4/40: FC=100|FS=forward|Red=lda/2|Out=None|Scl=None|Sex=off

FC=100|FS=forward|Red=lda/2|Out=None|Scl=None|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [14:38<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [12:35<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [12:27<?, ?it/s]

      → 2454 Rows in 1112.0s
    → Run 5/40: FC=100|FS=lasso|Red=lda/5|Out=zscore|Scl=standard|Sex=on

FC=100|FS=lasso|Red=lda/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 35.0s
    → Run 6/40: FC=100|FS=univariate|Red=pca/10|Out=zscore|Scl=robust|Sex=off

FC=100|FS=univariate|Red=pca/10|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 6.3s
    → Run 7/40: FC=100|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off

FC=100|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [37:07<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [18:34<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [17:57<?, ?it/s]

      → 2454 Rows in 1239.3s
    → Run 8/40: FC=100|FS=univariate|Red=umap/3|Out=zscore|Scl=None|Sex=on

FC=100|FS=univariate|Red=umap/3|Out=zscore|Scl=None|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 115.6s
    → Run 9/40: FC=50|FS=univariate|Red=umap/3|Out=None|Scl=None|Sex=off

FC=50|FS=univariate|Red=umap/3|Out=None|Scl=None|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 117.0s
    → Run 10/40: FC=50|FS=random_forest|Red=lda/3|Out=zscore|Scl=robust|Sex=off

FC=50|FS=random_forest|Red=lda/3|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 21.7s
    → Run 11/40: FC=50|FS=univariate|Red=lda/3|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=lda/3|Out=clip|Scl=None|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [25:03<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [04:21<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [02:24<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [00:24<?, ?it/s]

      → 2454 Rows in 4.6s
    → Run 12/40: FC=50|FS=univariate|Red=pca/5|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=pca/5|Out=clip|Scl=None|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 4.2s
    → Run 13/40: FC=50|FS=variance|Red=umap/10|Out=clip|Scl=robust|Sex=on

FC=50|FS=variance|Red=umap/10|Out=clip|Scl=robust|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 146.8s
    → Run 14/40: FC=50|FS=univariate|Red=umap/5|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=umap/5|Out=clip|Scl=None|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [02:44<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [02:37<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [02:30<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 129.3s
    → Run 15/40: FC=50|FS=variance|Red=lda/5|Out=zscore|Scl=None|Sex=on

FC=50|FS=variance|Red=lda/5|Out=zscore|Scl=None|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 3.9s
    → Run 16/40: FC=50|FS=variance|Red=umap/5|Out=zscore|Scl=None|Sex=on

FC=50|FS=variance|Red=umap/5|Out=zscore|Scl=None|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 129.2s
    → Run 17/40: FC=50|FS=variance|Red=lda/3|Out=None|Scl=robust|Sex=off

FC=50|FS=variance|Red=lda/3|Out=None|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [04:32<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [02:20<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [02:12<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 5.9s
    → Run 18/40: FC=50|FS=lasso|Red=lda/10|Out=clip|Scl=robust|Sex=off

FC=50|FS=lasso|Red=lda/10|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 38.8s
    → Run 19/40: FC=20|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off

FC=20|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 233.5s
    → Run 20/40: FC=20|FS=univariate|Red=lda/5|Out=clip|Scl=robust|Sex=off

FC=20|FS=univariate|Red=lda/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [04:50<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [04:41<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [03:58<?, ?it/s]

      → 2454 Rows in 5.9s
    → Run 21/40: FC=20|FS=lasso|Red=pca/3|Out=zscore|Scl=None|Sex=off

FC=20|FS=lasso|Red=pca/3|Out=zscore|Scl=None|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 38.4s
    → Run 22/40: FC=20|FS=random_forest|Red=umap/2|Out=clip|Scl=None|Sex=off

FC=20|FS=random_forest|Red=umap/2|Out=clip|Scl=None|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 129.1s
    → Run 23/40: FC=20|FS=variance|Red=umap/10|Out=zscore|Scl=None|Sex=off

FC=20|FS=variance|Red=umap/10|Out=zscore|Scl=None|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [03:50<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [03:40<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [02:57<?, ?it/s]

      → 2454 Rows in 132.6s
    → Run 24/40: FC=15|FS=forward|Red=umap/5|Out=None|Scl=standard|Sex=on

FC=15|FS=forward|Red=umap/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 202.6s
    → Run 25/40: FC=15|FS=variance|Red=umap/3|Out=zscore|Scl=robust|Sex=off

FC=15|FS=variance|Red=umap/3|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 114.6s
    → Run 26/40: FC=15|FS=forward|Red=lda/10|Out=clip|Scl=standard|Sex=off

FC=15|FS=forward|Red=lda/10|Out=clip|Scl=standard|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [08:26<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [06:08<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [02:40<?, ?it/s]

      → 2454 Rows in 81.1s
    → Run 27/40: FC=15|FS=lasso|Red=pca/10|Out=zscore|Scl=robust|Sex=off

FC=15|FS=lasso|Red=pca/10|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 37.7s
    → Run 28/40: FC=15|FS=random_forest|Red=pca/2|Out=clip|Scl=robust|Sex=on

FC=15|FS=random_forest|Red=pca/2|Out=clip|Scl=robust|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 26.9s
    → Run 29/40: FC=10|FS=variance|Red=pca/2|Out=None|Scl=standard|Sex=on

FC=10|FS=variance|Red=pca/2|Out=None|Scl=standard|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [02:45<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [01:18<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [00:35<?, ?it/s]

      → 2454 Rows in 3.9s
    → Run 30/40: FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=on

FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 5.3s
    → Run 31/40: FC=10|FS=random_forest|Red=lda/10|Out=None|Scl=robust|Sex=on

FC=10|FS=random_forest|Red=lda/10|Out=None|Scl=robust|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 26.6s
    → Run 32/40: FC=10|FS=variance|Red=umap/5|Out=clip|Scl=robust|Sex=on

FC=10|FS=variance|Red=umap/5|Out=clip|Scl=robust|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 131.3s
    → Run 33/40: FC=10|FS=univariate|Red=umap/5|Out=None|Scl=standard|Sex=on

FC=10|FS=univariate|Red=umap/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [03:11<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [03:01<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [02:50<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [02:17<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 128.0s
    → Run 34/40: FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=off

FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 3.6s
    → Run 35/40: FC=10|FS=forward|Red=lda/3|Out=None|Scl=standard|Sex=off

FC=10|FS=forward|Red=lda/3|Out=None|Scl=standard|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 52.0s
    → Run 36/40: FC=5|FS=random_forest|Red=lda/2|Out=clip|Scl=None|Sex=on

FC=5|FS=random_forest|Red=lda/2|Out=clip|Scl=None|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [03:26<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [01:11<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [01:01<?, ?it/s]

      → 2454 Rows in 24.3s
    → Run 37/40: FC=5|FS=lasso|Red=umap/5|Out=zscore|Scl=standard|Sex=on

FC=5|FS=lasso|Red=umap/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 155.5s
    → Run 38/40: FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on

FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 3.7s
    → Run 39/40: FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off

FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/2454 [03:58<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [03:26<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [00:43<?, ?it/s]

      → 2454 Rows in 159.1s
    → Run 40/40: FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on

FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on:   0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

  0%|          | 0/2454 [00:00<?, ?it/s]

      → 2454 Rows in 13.7s
  ✅ Fertig für mountain_lion, Parquet: C:\Users\Frede\OneDrive\Projects and Disschaptors\FIT_package\results\data\pairwise_comp_all_species_experiment\mountain_lion_all_results_combined.parquet

🔄 Processing species: white_rhino
  → 113 numerische Features
  Summary der Trail-Längen:

,sub_size,n_animals,n_trails,avg_comp_per_ind_same,sd_comp_per_ind_same,avg_comp_per_ind_diff,sd_comp_per_ind_diff,ratio_same_to_diff
0,9,19,32,NaN,NaN,NaN,NaN,NaN
1,7,19,32,NaN,NaN,NaN,NaN,NaN
2,5,19,34,NaN,NaN,NaN,NaN,NaN
3,3,20,37,NaN,NaN,NaN,NaN,NaN
4,2,20,37,NaN,NaN,NaN,NaN,NaN
5,Total,20,3185,18.75,9.579996,281.0,71.961978,0.133452

  → Noch offen: 40/52 Runs
    → Run 1/40: FC=200|FS=variance|Red=umap/3|Out=clip|Scl=standard|Sex=on

FC=200|FS=variance|Red=umap/3|Out=clip|Scl=standard|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 413.1s

Processing Pairs:   0%|          | 0/2454 [10:01<?, ?it/s]
Processing Pairs:   0%|          | 0/2454 [07:15<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [06:53<?, ?it/s]

    → Run 2/40: FC=200|FS=univariate|Red=pca/5|Out=None|Scl=robust|Sex=on

FC=200|FS=univariate|Red=pca/5|Out=None|Scl=robust|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 10.9s
    → Run 3/40: FC=200|FS=univariate|Red=pca/10|Out=clip|Scl=robust|Sex=off

FC=200|FS=univariate|Red=pca/10|Out=clip|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 10.7s
    → Run 4/40: FC=100|FS=forward|Red=lda/2|Out=None|Scl=None|Sex=off

FC=100|FS=forward|Red=lda/2|Out=None|Scl=None|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [09:48<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [09:36<?, ?it/s]

      → 3185 Rows in 985.4s
    → Run 5/40: FC=100|FS=lasso|Red=lda/5|Out=zscore|Scl=standard|Sex=on

FC=100|FS=lasso|Red=lda/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 44.8s
    → Run 6/40: FC=100|FS=univariate|Red=pca/10|Out=zscore|Scl=robust|Sex=off

FC=100|FS=univariate|Red=pca/10|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 10.1s
    → Run 7/40: FC=100|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off

FC=100|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [24:03<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [07:35<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [06:48<?, ?it/s]

      → 3185 Rows in 1399.6s
    → Run 8/40: FC=100|FS=univariate|Red=umap/3|Out=zscore|Scl=None|Sex=on

FC=100|FS=univariate|Red=umap/3|Out=zscore|Scl=None|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 416.4s
    → Run 9/40: FC=50|FS=univariate|Red=umap/3|Out=None|Scl=None|Sex=off

FC=50|FS=univariate|Red=umap/3|Out=None|Scl=None|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [36:19<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [12:55<?, ?it/s]

      → 3185 Rows in 404.1s
    → Run 10/40: FC=50|FS=random_forest|Red=lda/3|Out=zscore|Scl=robust|Sex=off

FC=50|FS=random_forest|Red=lda/3|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 34.6s
    → Run 11/40: FC=50|FS=univariate|Red=lda/3|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=lda/3|Out=clip|Scl=None|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 9.8s
    → Run 12/40: FC=50|FS=univariate|Red=pca/5|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=pca/5|Out=clip|Scl=None|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [07:52<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [01:03<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [00:23<?, ?it/s]

      → 3185 Rows in 10.1s
    → Run 13/40: FC=50|FS=variance|Red=umap/10|Out=clip|Scl=robust|Sex=on

FC=50|FS=variance|Red=umap/10|Out=clip|Scl=robust|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 489.5s
    → Run 14/40: FC=50|FS=univariate|Red=umap/5|Out=clip|Scl=None|Sex=on

FC=50|FS=univariate|Red=umap/5|Out=clip|Scl=None|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 439.9s
    → Run 15/40: FC=50|FS=variance|Red=lda/5|Out=zscore|Scl=None|Sex=on

FC=50|FS=variance|Red=lda/5|Out=zscore|Scl=None|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [16:03<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [15:46<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [07:30<?, ?it/s]

      → 3185 Rows in 10.3s
    → Run 16/40: FC=50|FS=variance|Red=umap/5|Out=zscore|Scl=None|Sex=on

FC=50|FS=variance|Red=umap/5|Out=zscore|Scl=None|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 445.6s
    → Run 17/40: FC=50|FS=variance|Red=lda/3|Out=None|Scl=robust|Sex=off

FC=50|FS=variance|Red=lda/3|Out=None|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 8.4s

Processing Pairs:   0%|          | 0/3185 [08:04<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [07:46<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [00:13<?, ?it/s]

    → Run 18/40: FC=50|FS=lasso|Red=lda/10|Out=clip|Scl=robust|Sex=off

FC=50|FS=lasso|Red=lda/10|Out=clip|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 61.1s
    → Run 19/40: FC=20|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off

FC=20|FS=forward|Red=umap/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 549.2s
    → Run 20/40: FC=20|FS=univariate|Red=lda/5|Out=clip|Scl=robust|Sex=off

FC=20|FS=univariate|Red=lda/5|Out=clip|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [10:35<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [09:25<?, ?it/s]

      → 3185 Rows in 8.9s
    → Run 21/40: FC=20|FS=lasso|Red=pca/3|Out=zscore|Scl=None|Sex=off

FC=20|FS=lasso|Red=pca/3|Out=zscore|Scl=None|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 40.6s
    → Run 22/40: FC=20|FS=random_forest|Red=umap/2|Out=clip|Scl=None|Sex=off

FC=20|FS=random_forest|Red=umap/2|Out=clip|Scl=None|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 418.8s
    → Run 23/40: FC=20|FS=variance|Red=umap/10|Out=zscore|Scl=None|Sex=off

FC=20|FS=variance|Red=umap/10|Out=zscore|Scl=None|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [11:13<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [10:55<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [10:05<?, ?it/s]

      → 3185 Rows in 482.7s
    → Run 24/40: FC=15|FS=forward|Red=umap/5|Out=None|Scl=standard|Sex=on

FC=15|FS=forward|Red=umap/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 515.0s
    → Run 25/40: FC=15|FS=variance|Red=umap/3|Out=zscore|Scl=robust|Sex=off

FC=15|FS=variance|Red=umap/3|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 406.4s
    → Run 26/40: FC=15|FS=forward|Red=lda/10|Out=clip|Scl=standard|Sex=off

FC=15|FS=forward|Red=lda/10|Out=clip|Scl=standard|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [24:03<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [15:49<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [07:02<?, ?it/s]

      → 3185 Rows in 85.8s
    → Run 27/40: FC=15|FS=lasso|Red=pca/10|Out=zscore|Scl=robust|Sex=off

FC=15|FS=lasso|Red=pca/10|Out=zscore|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 42.7s
    → Run 28/40: FC=15|FS=random_forest|Red=pca/2|Out=clip|Scl=robust|Sex=on

FC=15|FS=random_forest|Red=pca/2|Out=clip|Scl=robust|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [03:01<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [01:22<?, ?it/s]

      → 3185 Rows in 35.9s
    → Run 29/40: FC=10|FS=variance|Red=pca/2|Out=None|Scl=standard|Sex=on

FC=10|FS=variance|Red=pca/2|Out=None|Scl=standard|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 8.8s
    → Run 30/40: FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=on

FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 9.5s
    → Run 31/40: FC=10|FS=random_forest|Red=lda/10|Out=None|Scl=robust|Sex=on

FC=10|FS=random_forest|Red=lda/10|Out=None|Scl=robust|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [01:53<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [01:03<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [00:40<?, ?it/s]

      → 3185 Rows in 33.6s
    → Run 32/40: FC=10|FS=variance|Red=umap/5|Out=clip|Scl=robust|Sex=on

FC=10|FS=variance|Red=umap/5|Out=clip|Scl=robust|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 456.9s
    → Run 33/40: FC=10|FS=univariate|Red=umap/5|Out=None|Scl=standard|Sex=on

FC=10|FS=univariate|Red=umap/5|Out=None|Scl=standard|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 432.1s
    → Run 34/40: FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=off

FC=10|FS=univariate|Red=lda/5|Out=None|Scl=standard|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [16:10<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [15:21<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [07:29<?, ?it/s]

      → 3185 Rows in 9.5s
    → Run 35/40: FC=10|FS=forward|Red=lda/3|Out=None|Scl=standard|Sex=off

FC=10|FS=forward|Red=lda/3|Out=None|Scl=standard|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 60.2s
    → Run 36/40: FC=5|FS=random_forest|Red=lda/2|Out=clip|Scl=None|Sex=on

FC=5|FS=random_forest|Red=lda/2|Out=clip|Scl=None|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [02:13<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [01:47<?, ?it/s]

      → 3185 Rows in 32.5s
    → Run 37/40: FC=5|FS=lasso|Red=umap/5|Out=zscore|Scl=standard|Sex=on

FC=5|FS=lasso|Red=umap/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 476.2s
    → Run 38/40: FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on

FC=5|FS=variance|Red=lda/5|Out=zscore|Scl=standard|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 9.5s
    → Run 39/40: FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off

FC=5|FS=lasso|Red=umap/10|Out=None|Scl=robust|Sex=off:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/3185 [15:00<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [14:10<?, ?it/s]
Processing Pairs:   0%|          | 0/3185 [05:56<?, ?it/s]

      → 3185 Rows in 481.0s
    → Run 40/40: FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on

FC=2|FS=forward|Red=pca/5|Out=clip|Scl=robust|Sex=on:   0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

  0%|          | 0/3185 [00:00<?, ?it/s]

      → 3185 Rows in 16.6s
  ✅ Fertig für white_rhino, Parquet: C:\Users\Frede\OneDrive\Projects and Disschaptors\FIT_package\results\data\pairwise_comp_all_species_experiment\white_rhino_all_results_combined.parquet

🎉 Fertig – Gesamt-Parquet erzeugt:
   C:\Users\Frede\OneDrive\Projects and Disschaptors\FIT_package\results\data\pairwise_comp_all_species_experiment\all_species_all_results_combined.parquet

,feature_count,selection_method,reducer,n_components,outlier_method,scaler_method,use_sex,trail_a_id,trail_b_id,samples_a,...,mean_mahalanobis_within_b,median_mahalanobis_within_b,avg_proba_A_0,avg_proba_A_1,avg_proba_B_0,avg_proba_B_1,avg_proba_R_0,avg_proba_R_1,selected_features,selected_scores
0,200,univariate,pca,3,clip,standard,False,gimpy_9c0,sean_9c0,"[268, 197, 191, 198, 269, 201, 199, 200, 195]",...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None
1,200,univariate,pca,3,clip,standard,False,gimpy_7c0,sean_7c0,"[195, 191, 197, 200, 269, 198, 194]",...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None
2,200,univariate,pca,3,clip,standard,False,gimpy_5c0,sean_5c0,"[195, 197, 198, 200, 191]",...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None
3,200,univariate,pca,3,clip,standard,False,gimpy_3c0,sean_3c0,"[191, 198, 269]",...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None
4,200,univariate,pca,3,clip,standard,False,gimpy_3c0,sean_3c1,"[191, 198, 269]",...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None

In [ ]:
# %% 
import time, os, json
from pathlib import Path
import pandas as pd
import numpy as np
import itertools
from tqdm.notebook import tqdm
from tqdm_joblib import tqdm_joblib
from sklearn.model_selection import ParameterSampler


from FIT_python.pipeline_individual_id.pairwise_individual_id_pipeline import (
    run_all_pairwise_projections_parallel
)
from FIT_python.pipeline_individual_id.generate_trails_and_trailpairs import (
    generate_pairwise_comparisons_from_df
)

# %% 1) Basis-Pfade & Hyperparameter-Räume
splits_root = Path("C:/Users/Frede/OneDrive/Projects and Disschaptors/FIT_package/data/splits")
models_root = Path(r"C:\Users\Frede\OneDrive\Projects and Disschaptors\FIT_package\results\data\sex_models_best")
output_root = Path("C:/Users/Frede/OneDrive/Projects and Disschaptors/FIT_package/results/data/individual_id/_all_species_all_individuals_with_basline_fit")
output_root.mkdir(parents=True, exist_ok=True)



# BAseline FIT Method
baseline_feature_counts = [10, 12, 14, 16, 18, 20]

# Erzeuge alle Kombinationen für use_sex = False und True
baseline_models = pd.DataFrame(
    list(itertools.product(
        baseline_feature_counts,         # feature_count
        ["forward"],                     # selection_method
        ["lda"],                         # reducer
        [2],                             # n_components
        [None],                          # outlier_method
        [None],                          # scaler_method
        [False, True]                    # use_sex
    )),
    columns=[
        "feature_count",
        "selection_method",
        "reducer",
        "n_components",
        "outlier_method",
        "scaler_method",
        "use_sex"
    ]
)



feature_counts    = [2,5,8,15,50,100,200]
selection_methods = ["random_forest","forward","univariate","variance","lasso"]
reducers          = ["pca","lda","umap"]
n_components_list = [2, 3, 5, 10]
outlier_methods   = [None,"clip","zscore"]
scaler_methods    = [None,"standard","robust"]
use_sex_opts      = [False]
n_jobs            = 6

# %% 2) Grid erzeugen & 100 auswählen via ParameterSampler
from sklearn.model_selection import ParameterSampler

param_dist = {
    "feature_count":    feature_counts,
    "selection_method": selection_methods,
    "reducer":          reducers,
    "n_components":     n_components_list,
    "outlier_method":   outlier_methods,
    "scaler_method":    scaler_methods,
    "use_sex":          use_sex_opts,
}

# Ziehe 138 zufällige Konfigurationen
sampled_grid = pd.DataFrame(
    list(ParameterSampler(param_dist, n_iter=20, random_state=42))
)

# Sortieren wie gehabt
sampled_grid = sampled_grid.sort_values("feature_count", ascending=False).reset_index(drop=True)

# ➕ Anhängen an das bestehende Grid
sampled_grid_extended = pd.concat([sampled_grid, baseline_models], ignore_index=True)

# 📊 Optional sortieren
sampled_grid_extended = sampled_grid_extended.sort_values("feature_count", ascending=False).reset_index(drop=True)

# %% 3) Ergebnis-Datei initialisieren oder laden
out_fp = output_root / "all_species_all_results_combined.parquet"
if out_fp.exists():
    df_completed = pd.read_parquet(out_fp)
else:
    df_completed = pd.DataFrame()  # wird später mit den ersten Runs gefüllt

# %% 4) Spezies-Schleife
for species_dir in sorted(splits_root.iterdir()):
    if not species_dir.is_dir(): 
        continue
    species = species_dir.name
    print(f"\n🔄 Processing species: {species}")

    # 4.1) Daten laden
    df = pd.read_csv(species_dir / "train.csv")

    # 4.2) Feature-Spalten wählen
    if species == "eurasian_otter_(1)":
        feature_cols = [
            c for c in df.columns 
            if c.startswith(("dist","ang","t")) and pd.api.types.is_numeric_dtype(df[c])
        ]
    else:
        feature_cols = [
            c for c in df.columns[5:]
            if pd.api.types.is_numeric_dtype(df[c])
        ]
    print(f"  → {len(feature_cols)} numerische Features")

    # 4.3) Pairs & Summary generieren (einmal pro Spezies)
    comps, summary = generate_pairwise_comparisons_from_df(
        df,
        id_col="individual_id",
        chunk_size=10,
        trail_size_list=[9,7,5,3,2],
        max_individuals=20,
        max_trails_per_animal=3,
        n_folds=3,
        random_state=42
    )
    print("  Summary der Trail-Längen:")
    display(summary)

    # 4.4) Hyper-Parameter-Loop
    for idx, row in sampled_grid_extended.iterrows():
        fc, sel, red, nc, out, scl, sex = (
            int(row.feature_count),
            row.selection_method,
            row.reducer,
            int(row.n_components),
            row.outlier_method,
            row.scaler_method,
            bool(row.use_sex)
        )
        # Key-Tuple, um zu prüfen, ob wir das schon berechnet haben
        run_key = (
            species, fc, sel, red, nc, out, scl, sex
        )
        already = False
        if not df_completed.empty:
            # existiert mindestens eine Zeile mit genau diesen Parametern?
            mask = (
                (df_completed["species"] == species) &
                (df_completed["feature_count"] == fc) &
                (df_completed["selection_method"] == sel) &
                (df_completed["reducer"] == red) &
                (df_completed["n_components"] == nc) &
                (df_completed["outlier_method"] == out) &
                (df_completed["scaler_method"] == scl) &
                (df_completed["use_sex"] == sex)
            )
            if mask.any():
                already = True

        if already:
            print(f"    → SKIP {idx+1}/{len(sampled_grid)}  (bereits vorhanden)")
            continue

        desc = (
            f"FC={fc}|FS={sel}|Red={red}/{nc}|Out={out}|Scl={scl}|Sex={'on' if sex else 'off'}"
        )
        print(f"    → Run {idx+1}/{len(sampled_grid)}: {desc}")
        t0 = time.time()

        with tqdm_joblib(tqdm(desc=desc, total=len(comps), leave=False)):
            res = run_all_pairwise_projections_parallel(
                comparisons=comps,
                df=df,
                feature_cols=feature_cols,
                k_features=fc,
                selection_method=sel,
                reducers=[red],
                n_components=[nc],
                outlier_methods=out,
                scaler_methods=scl,
                use_sexmodel_prediction=sex,
                sexmodel_path=(
                    models_root / f"{species}.joblib"
                    if sex else None
                ),
                debug=False,
                n_jobs=n_jobs
            )
        dur = time.time() - t0
        print(f"      → {len(res)} Rows in {dur:.1f}s")

        # 4.5) Results anreichern und anhängen
        df_run = pd.DataFrame(res)
        df_run["species"]          = species
        df_run["duration_s"]       = dur
        df_run["feature_count"]    = fc
        df_run["selection_method"] = sel
        df_run["reducer"]          = red
        df_run["n_components"]     = nc
        df_run["outlier_method"]   = out
        df_run["scaler_method"]    = scl
        df_run["use_sex"]          = sex

        # an df_completed in memory anhängen
        df_completed = pd.concat([df_completed, df_run], ignore_index=True)
        # sofort ins Parquet schreiben
        df_completed.to_parquet(out_fp, index=False)

# %% 5) Abschließende Kontrolle
print(f"\n🎉 Fertig – Gesamt-Parquet (inkrementell) aktualisiert unter:\n {out_fp}")
display(df_completed.head())