In [ ]:
# %%
import pandas as pd
import json
from pathlib import Path
from FIT_python.pipeline_individual_id.generate_trails_and_trailpairs import (
    generate_pairwise_comparisons_from_df
)

# --- 1) Pfade & Daten einlesen ---
data_path = Path("C:/Users/Frede/OneDrive/Projects and Disschaptors/FIT_package/data/splits/eurasian_otter_(1)")
df = pd.read_csv(data_path / "train.csv")

# --- 2) Comparisons & Summary erzeugen ---
#    chunk_size: in wie große nicht-überlappende Chunks wir die Prints unterteilen
#    trail_size_list: welche Trail-Längen (z.B. 7, 5, 3) wir aus jedem Chunk ziehen
comparisons, summary = generate_pairwise_comparisons_from_df(
    df,
    id_col="individual_id",
    chunk_size=10,
    trail_size_list=[10,8,6,4,2],
    max_individuals=10,
    max_trails_per_animal=5,
    n_folds=3,
    random_state=42
)

# --- 3) Summary anzeigen ---
print("=== Summary pro Trail-Länge ===")
display(summary)

# --- 4) Gesamtzahl der Vergleichspaare ---
print(f"→ Insgesamt {len(comparisons)} Vergleichspaare erzeugt.")

# --- 5) Erste 5 Einträge in comparisons inspizieren ---
print("\n=== Beispiel-Einträge ===")
for comp in comparisons[:5]:
    print(json.dumps(comp, indent=2, sort_keys=True))

=== Summary pro Trail-Länge ===

,sub_size,n_animals,n_trails,avg_comp_per_ind_same,sd_comp_per_ind_same,avg_comp_per_ind_diff,sd_comp_per_ind_diff,ratio_same_to_diff
0,10,6,9,NaN,NaN,NaN,NaN,NaN
1,8,8,11,NaN,NaN,NaN,NaN,NaN
2,6,10,14,NaN,NaN,NaN,NaN,NaN
3,4,10,16,NaN,NaN,NaN,NaN,NaN
4,2,10,18,NaN,NaN,NaN,NaN,NaN
5,Total,10,559,13.0,14.181365,85.8,33.644547,0.30303

→ Insgesamt 559 Vergleichspaare erzeugt.

=== Beispiel-Einträge ===
{
  "chunk_a": 0,
  "chunk_b": 0,
  "diff_size": 0,
  "fold": 0,
  "ind_a": "rosie",
  "ind_b": "innsbruck_1",
  "same_individual": false,
  "same_sex": false,
  "samples_a": [
    44,
    39,
    31,
    34,
    27,
    32,
    35,
    28,
    48,
    43
  ],
  "samples_b": [
    200,
    207,
    217,
    198,
    211,
    209,
    212,
    218,
    202,
    199
  ],
  "trail_a_id": "rosie_10c0",
  "trail_b_id": "innsbruck_1_10c0",
  "trail_size_a": 10,
  "trail_size_b": 10
}
{
  "chunk_a": 0,
  "chunk_b": 1,
  "diff_size": 0,
  "fold": 0,
  "ind_a": "rosie",
  "ind_b": "innsbruck_1",
  "same_individual": false,
  "same_sex": false,
  "samples_a": [
    44,
    39,
    31,
    34,
    27,
    32,
    35,
    28,
    48,
    43
  ],
  "samples_b": [
    206,
    213,
    216,
    201,
    208,
    214,
    210,
    196,
    204,
    205
  ],
  "trail_a_id": "rosie_10c0",
  "trail_b_id": "innsbruck_1_10c1",
  "trail_size_a": 10,
  "trail_size_b": 10
}
{
  "chunk_a": 1,
  "chunk_b": 0,
  "diff_size": 0,
  "fold": 1,
  "ind_a": "rosie",
  "ind_b": "innsbruck_1",
  "same_individual": false,
  "same_sex": false,
  "samples_a": [
    41,
    29,
    45,
    30,
    46,
    40,
    47,
    33,
    42,
    37
  ],
  "samples_b": [
    200,
    207,
    217,
    198,
    211,
    209,
    212,
    218,
    202,
    199
  ],
  "trail_a_id": "rosie_10c1",
  "trail_b_id": "innsbruck_1_10c0",
  "trail_size_a": 10,
  "trail_size_b": 10
}
{
  "chunk_a": 1,
  "chunk_b": 1,
  "diff_size": 0,
  "fold": 0,
  "ind_a": "rosie",
  "ind_b": "innsbruck_1",
  "same_individual": false,
  "same_sex": false,
  "samples_a": [
    41,
    29,
    45,
    30,
    46,
    40,
    47,
    33,
    42,
    37
  ],
  "samples_b": [
    206,
    213,
    216,
    201,
    208,
    214,
    210,
    196,
    204,
    205
  ],
  "trail_a_id": "rosie_10c1",
  "trail_b_id": "innsbruck_1_10c1",
  "trail_size_a": 10,
  "trail_size_b": 10
}
{
  "chunk_a": 0,
  "chunk_b": 0,
  "diff_size": 0,
  "fold": 1,
  "ind_a": "rosie",
  "ind_b": "innsbruck_1",
  "same_individual": false,
  "same_sex": false,
  "samples_a": [
    31,
    39,
    48,
    43,
    32,
    28,
    34,
    44
  ],
  "samples_b": [
    202,
    200,
    199,
    211,
    207,
    217,
    212,
    209
  ],
  "trail_a_id": "rosie_8c0",
  "trail_b_id": "innsbruck_1_8c0",
  "trail_size_a": 8,
  "trail_size_b": 8
}

import itertools
import pandas as pd'forward', 'random_forest', 'variance', 'univariate', 'lasso'

In [1]:
import itertools
import pandas as pd

# Parameterlisten
feature_counts    = [10, 15, 20, 50, 100, 200]
selection_methods = ["random_forest", "forward", "univariate", "variance", "lasso"]
reducers          = ["pca", "lda", "umap"]
n_components_list = [2, 3, 5, 10]
outlier_methods   = [None, "clip", "zscore"]
scaler_methods    = [None, "standard", "robust"]
use_sex_opts      = [False, True]

# 1) Vollständiges Grid erzeugen
grid = list(itertools.product(
    feature_counts,
    selection_methods,
    reducers,
    n_components_list,
    outlier_methods,
    scaler_methods,
    use_sex_opts
))

# 2) In DataFrame umwandeln und nach feature_count absteigend sortieren
df_grid = (
    pd.DataFrame(grid, columns=[
        "feature_count",
        "selection_method",
        "reducer",
        "n_components",
        "outlier_method",
        "scaler_method",
        "use_sex"
    ])
    .sort_values(by="feature_count", ascending=False)
    .reset_index(drop=True)
)

# 3) Zufällig 100 Kombinationen ziehen
df_sample = df_grid.sample(n=100, random_state=42).reset_index(drop=True)

# 4) Ausgabe
print(f"Total combinations: {len(df_grid)}")
print("Beispiel der 100 zufällig ausgewählten Kombinationen (mit höchster feature_count zuerst im Grid):")
display(df_sample)

# Parameterlisten
feature_counts    = [10, 15, 20, 50, 100, 200]
selection_methods = ["random_forest", "forward", "univariate", "variance", "lasso"]
reducers          = ["pca", "lda", "umap"]
n_components_list = [2, 3, 5, 10]
outlier_methods   = [None, "clip", "zscore"]
scaler_methods    = [None, "standard", "robust"]
use_sex_opts      = [False, True]

# 1) Vollständiges Grid erzeugen
grid = list(itertools.product(
    feature_counts,
    selection_methods,
    reducers,
    n_components_list,
    outlier_methods,
    scaler_methods,
    use_sex_opts
))

# 2) In DataFrame umwandeln und nach feature_count absteigend sortieren
# 1) Vollständiges Grid erzeugen und nach feature_count absteigend sortieren
df_grid = (
    pd.DataFrame(itertools.product(
        feature_counts,
        selection_methods,
        reducers,
        n_components_list,
        outlier_methods,
        scaler_methods,
        use_sex_opts
    ),
    columns=[
        "feature_count",
        "selection_method",
        "reducer",
        "n_components",
        "outlier_method",
        "scaler_method",
        "use_sex"
    ])
    .sort_values("feature_count", ascending=False)
    .reset_index(drop=True)
)

# 2) 100 Zufalls-Kombinationen ziehen …
df_sample = df_grid.sample(n=100, random_state=42)

# 3) … und dann innerhalb der 100er-Stichprobe wieder nach feature_count sortieren
df_sample = df_sample.sort_values("feature_count", ascending=False).reset_index(drop=True)

display(df_sample)

Total combinations: 6480
Beispiel der 100 zufällig ausgewählten Kombinationen (mit höchster feature_count zuerst im Grid):

,feature_count,selection_method,reducer,n_components,outlier_method,scaler_method,use_sex
0,20,variance,lda,10,None,standard,True
1,20,forward,umap,5,None,robust,False
2,100,random_forest,pca,2,clip,robust,True
3,200,variance,pca,10,clip,standard,True
4,20,lasso,pca,2,zscore,robust,True
...,...,...,...,...,...,...,...
95,15,univariate,pca,3,None,robust,True
96,50,forward,pca,2,None,robust,True
97,100,univariate,umap,10,clip,None,True
98,10,univariate,lda,10,None,standard,False
99,200,lasso,pca,2,zscore,standard,False

,feature_count,selection_method,reducer,n_components,outlier_method,scaler_method,use_sex
0,200,variance,pca,10,clip,standard,True
1,200,random_forest,lda,3,clip,robust,True
2,200,variance,pca,3,clip,robust,True
3,200,random_forest,pca,3,zscore,None,True
4,200,univariate,umap,3,clip,robust,True
...,...,...,...,...,...,...,...
95,10,random_forest,umap,3,zscore,None,True
96,10,forward,lda,2,clip,standard,True
97,10,forward,pca,10,zscore,robust,True
98,10,lasso,lda,3,zscore,None,False
99,10,univariate,lda,10,None,standard,False

In [4]:
# %% 
import time, os, json
from pathlib import Path
import pandas as pd
import numpy as np
import itertools
from tqdm.notebook import tqdm
from tqdm_joblib import tqdm_joblib

from FIT_python.pipeline_individual_id.pairwise_individual_id_pipeline import (
    run_all_pairwise_projections_parallel
)
from FIT_python.pipeline_individual_id.generate_trails_and_trailpairs import (
    generate_pairwise_comparisons_from_df
)

# %% 1) Basis-Setup
data_path   = Path("C:/Users/Frede/OneDrive/Projects and Disschaptors/FIT_package/data/splits/eurasian_otter_(1)")
df          = pd.read_csv(data_path / "train.csv")
output_dir  = Path("C:/Users/Frede/OneDrive/Projects and Disschaptors/FIT_package/results/data")
output_dir.mkdir(parents=True, exist_ok=True)
results_fp  = output_dir / "all_results_combined.parquet"

# Feature-Spalten
feature_cols = [
    c for c in df.columns 
    if c.startswith(("dist","ang","t")) and pd.api.types.is_numeric_dtype(df[c])
]

# Hyper-Parameter-Räume
feature_counts    = [2,5,10, 15, 20, 50, 100, 200]
selection_methods = ["random_forest","forward","univariate","variance","lasso"]
reducers          = ["pca","lda","umap"]
n_components_list = [2, 3, 5, 10]
outlier_methods   = [None,"clip","zscore"]
scaler_methods    = [None,"standard","robust"]
use_sex_opts      = [False, True]
n_jobs            = -1

# %% 2) komplettes Grid erstellen & sortieren
df_grid = (
    pd.DataFrame(
        itertools.product(
            feature_counts,
            selection_methods,
            reducers,
            n_components_list,
            outlier_methods,
            scaler_methods,
            use_sex_opts
        ),
        columns=[
            "feature_count",
            "selection_method",
            "reducer",
            "n_components",
            "outlier_method",
            "scaler_method",
            "use_sex"
        ]
    )
    .sort_values("feature_count", ascending=False)
    .reset_index(drop=True)
)

# 3) 100 Zufalls-Kombis ziehen, danach wieder sortieren
df_sample = df_grid.sample(n=100, random_state=42)
df_sample = df_sample.sort_values("feature_count", ascending=False).reset_index(drop=True)

# %% 4) bereits abgelaufene Kombis herausfiltern (falls Parquet existiert)
if results_fp.exists():
    df_done = pd.read_parquet(results_fp, columns=[
        "feature_count","selection_method","reducer","n_components",
        "outlier_method","scaler_method","use_sex"
    ]).drop_duplicates()
    # merge-key auf allen sieben Spalten
    done_keys = set(tuple(r) for r in df_done.values)
    mask_todo = df_sample.apply(lambda row: tuple(row.values) not in done_keys, axis=1)
    df_todo   = df_sample[mask_todo].reset_index(drop=True)
else:
    df_todo = df_sample.copy()

print(f"→ {len(df_todo)}/{len(df_sample)} Kombinationen noch offen, wir starten jetzt.")

# %% 5) Comparisons einmalig erzeugen
comparisons, summary = generate_pairwise_comparisons_from_df(
    df,
    id_col="individual_id",
    chunk_size=7,
    trail_size_list=[7,5,3],
    max_individuals=5,
    max_trails_per_animal=2,
    n_folds=5,
    random_state=42
)
print("Summary der Trails pro Länge:")
display(summary)

# %% 6) Outer-Loop: jede Hyper-Kombi
for idx, params in df_todo.iterrows():
    fc   = int(params.feature_count)
    sel  = params.selection_method
    red  = params.reducer
    nc   = int(params.n_components)
    out  = params.outlier_method
    scl  = params.scaler_method
    sex  = bool(params.use_sex)

    descr = (
        f"FC={fc} | FS={sel} | Red={red}/{nc} | "
        f"Out={out} | Scl={scl} | Sex={'on' if sex else 'off'}"
    )
    print(f"\n→ Start Kombi {idx+1}/{len(df_todo)}: {descr}")
    t0 = time.time()

    # in inneren Loop ggf. parallel auf Pairs
    with tqdm_joblib(tqdm(desc=descr, total=len(comparisons), leave=False)):
        results = run_all_pairwise_projections_parallel(
            comparisons=comparisons,
            df=df,
            feature_cols=feature_cols,
            k_features=fc,
            selection_method=sel,
            reducers=[red],
            n_components=[nc],
            outlier_methods=out,
            scaler_methods=scl,
            use_sexmodel_prediction=sex,
            sexmodel_path=(
                r"C:\Users\Frede\OneDrive\Projects and Disschaptors\FIT_package\results\data\models\eurasian_otter_(1).joblib"
                if sex else None
            ),
            debug=False,
            n_jobs=n_jobs
        )

    dur = time.time() - t0
    print(f"→ Fertig in {dur:.1f}s, {len(results)} Rows.")

    # 7) Ergebnisse anhängen und persistent speichern
    df_run = pd.DataFrame(results)
    # An hyper-param-Spalten koppeln
    for col in df_todo.columns:
        df_run[col] = params[col]
    # Parquet: erst-anlauf oder append?
    if results_fp.exists():
        existing = pd.read_parquet(results_fp)
        full = pd.concat([existing, df_run], ignore_index=True)
    else:
        full = df_run
    full.to_parquet(results_fp, index=False)

print("✅ Alle ausstehenden Kombinationen abgearbeitet.")

→ 100/100 Kombinationen noch offen, wir starten jetzt.
Summary der Trails pro Länge:

,sub_size,n_animals,n_trails,avg_comp_per_ind_same,sd_comp_per_ind_same,avg_comp_per_ind_diff,sd_comp_per_ind_diff,ratio_same_to_diff
0,7,5,8,NaN,NaN,NaN,NaN,NaN
1,5,5,8,NaN,NaN,NaN,NaN,NaN
2,3,5,8,NaN,NaN,NaN,NaN,NaN
3,Total,5,102,5.4,4.929503,30.0,8.215838,0.36

→ Start Kombi 1/100: FC=200 | FS=variance | Red=umap/10 | Out=clip | Scl=standard | Sex=off

FC=200 | FS=variance | Red=umap/10 | Out=clip | Scl=standard | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s…

  0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 45.5s, 102 Rows.

→ Start Kombi 2/100: FC=200 | FS=lasso | Red=umap/10 | Out=zscore | Scl=None | Sex=on

FC=200 | FS=lasso | Red=umap/10 | Out=zscore | Scl=None | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:46<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 7.1s, 102 Rows.

→ Start Kombi 3/100: FC=200 | FS=forward | Red=lda/3 | Out=clip | Scl=None | Sex=off

FC=200 | FS=forward | Red=lda/3 | Out=clip | Scl=None | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:07<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 321.0s, 0 Rows.

→ Start Kombi 4/100: FC=200 | FS=variance | Red=lda/5 | Out=None | Scl=standard | Sex=off

FC=200 | FS=variance | Red=lda/5 | Out=None | Scl=standard | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [05:21<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 0.4s, 0 Rows.

→ Start Kombi 5/100: FC=200 | FS=variance | Red=umap/5 | Out=clip | Scl=robust | Sex=on

FC=200 | FS=variance | Red=umap/5 | Out=clip | Scl=robust | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 4.8s, 102 Rows.

→ Start Kombi 6/100: FC=200 | FS=random_forest | Red=pca/3 | Out=clip | Scl=standard | Sex=on

FC=200 | FS=random_forest | Red=pca/3 | Out=clip | Scl=standard | Sex=on:   0%|          | 0/102 [00:00<?, ?it…

  0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:01<?, ?it/s]

→ Fertig in 1.3s, 102 Rows.

→ Start Kombi 7/100: FC=200 | FS=random_forest | Red=lda/3 | Out=None | Scl=standard | Sex=on

FC=200 | FS=random_forest | Red=lda/3 | Out=None | Scl=standard | Sex=on:   0%|          | 0/102 [00:00<?, ?it…

  0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 1.2s, 0 Rows.

→ Start Kombi 8/100: FC=200 | FS=random_forest | Red=umap/5 | Out=clip | Scl=None | Sex=off

FC=200 | FS=random_forest | Red=umap/5 | Out=clip | Scl=None | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s…

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:01<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:05<?, ?it/s]

→ Fertig in 5.0s, 102 Rows.

→ Start Kombi 9/100: FC=100 | FS=univariate | Red=umap/3 | Out=zscore | Scl=None | Sex=on

FC=100 | FS=univariate | Red=umap/3 | Out=zscore | Scl=None | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 4.1s, 102 Rows.

→ Start Kombi 10/100: FC=100 | FS=lasso | Red=umap/2 | Out=None | Scl=standard | Sex=on

FC=100 | FS=lasso | Red=umap/2 | Out=None | Scl=standard | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:04<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 5.4s, 102 Rows.

→ Start Kombi 11/100: FC=100 | FS=lasso | Red=pca/5 | Out=None | Scl=standard | Sex=on

FC=100 | FS=lasso | Red=pca/5 | Out=None | Scl=standard | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:05<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 1.8s, 102 Rows.

→ Start Kombi 12/100: FC=100 | FS=variance | Red=pca/10 | Out=zscore | Scl=None | Sex=off

FC=100 | FS=variance | Red=pca/10 | Out=zscore | Scl=None | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:02<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 0.4s, 102 Rows.

→ Start Kombi 13/100: FC=100 | FS=lasso | Red=pca/10 | Out=zscore | Scl=None | Sex=off

FC=100 | FS=lasso | Red=pca/10 | Out=zscore | Scl=None | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 1.9s, 102 Rows.

→ Start Kombi 14/100: FC=100 | FS=forward | Red=pca/10 | Out=None | Scl=standard | Sex=off

FC=100 | FS=forward | Red=pca/10 | Out=None | Scl=standard | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:02<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 98.1s, 102 Rows.

→ Start Kombi 15/100: FC=100 | FS=forward | Red=lda/5 | Out=None | Scl=standard | Sex=on

FC=100 | FS=forward | Red=lda/5 | Out=None | Scl=standard | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [01:38<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 96.6s, 0 Rows.

→ Start Kombi 16/100: FC=100 | FS=lasso | Red=umap/10 | Out=zscore | Scl=None | Sex=on

FC=100 | FS=lasso | Red=umap/10 | Out=zscore | Scl=None | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [01:36<?, ?it/s]
Processing Pairs:   0%|          | 0/102 [03:46<?, ?it/s]
Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 5.8s, 102 Rows.

→ Start Kombi 17/100: FC=100 | FS=univariate | Red=pca/5 | Out=zscore | Scl=None | Sex=off

FC=100 | FS=univariate | Red=pca/5 | Out=zscore | Scl=None | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:06<?, ?it/s]
Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 0.5s, 102 Rows.

→ Start Kombi 18/100: FC=100 | FS=variance | Red=lda/10 | Out=clip | Scl=robust | Sex=on

FC=100 | FS=variance | Red=lda/10 | Out=clip | Scl=robust | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:01<?, ?it/s]
Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 0.8s, 0 Rows.

→ Start Kombi 19/100: FC=100 | FS=random_forest | Red=pca/10 | Out=clip | Scl=robust | Sex=off

FC=100 | FS=random_forest | Red=pca/10 | Out=clip | Scl=robust | Sex=off:   0%|          | 0/102 [00:00<?, ?it…

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:01<?, ?it/s]
Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 1.3s, 102 Rows.

→ Start Kombi 20/100: FC=100 | FS=univariate | Red=lda/5 | Out=clip | Scl=robust | Sex=on

FC=100 | FS=univariate | Red=lda/5 | Out=clip | Scl=robust | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:02<?, ?it/s]
Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 0.8s, 0 Rows.

→ Start Kombi 21/100: FC=100 | FS=forward | Red=umap/3 | Out=zscore | Scl=standard | Sex=off

FC=100 | FS=forward | Red=umap/3 | Out=zscore | Scl=standard | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s…

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:01<?, ?it/s]
Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 147.1s, 102 Rows.

→ Start Kombi 22/100: FC=50 | FS=forward | Red=pca/10 | Out=clip | Scl=standard | Sex=off

FC=50 | FS=forward | Red=pca/10 | Out=clip | Scl=standard | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [02:27<?, ?it/s]
Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 39.8s, 102 Rows.

→ Start Kombi 23/100: FC=50 | FS=forward | Red=umap/3 | Out=zscore | Scl=None | Sex=on

FC=50 | FS=forward | Red=umap/3 | Out=zscore | Scl=None | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 28.2s, 102 Rows.

→ Start Kombi 24/100: FC=50 | FS=random_forest | Red=lda/2 | Out=None | Scl=None | Sex=on

FC=50 | FS=random_forest | Red=lda/2 | Out=None | Scl=None | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 1.0s, 0 Rows.

→ Start Kombi 25/100: FC=50 | FS=forward | Red=lda/5 | Out=None | Scl=robust | Sex=off

FC=50 | FS=forward | Red=lda/5 | Out=None | Scl=robust | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 24.5s, 0 Rows.

→ Start Kombi 26/100: FC=50 | FS=variance | Red=lda/2 | Out=None | Scl=robust | Sex=off

FC=50 | FS=variance | Red=lda/2 | Out=None | Scl=robust | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:24<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 0.4s, 0 Rows.

→ Start Kombi 27/100: FC=50 | FS=lasso | Red=pca/10 | Out=clip | Scl=standard | Sex=off

FC=50 | FS=lasso | Red=pca/10 | Out=clip | Scl=standard | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 1.6s, 102 Rows.

→ Start Kombi 28/100: FC=50 | FS=variance | Red=umap/5 | Out=clip | Scl=standard | Sex=off

FC=50 | FS=variance | Red=umap/5 | Out=clip | Scl=standard | Sex=off:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:01<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

→ Fertig in 4.3s, 102 Rows.

→ Start Kombi 29/100: FC=50 | FS=univariate | Red=lda/3 | Out=zscore | Scl=robust | Sex=on

FC=50 | FS=univariate | Red=lda/3 | Out=zscore | Scl=robust | Sex=on:   0%|          | 0/102 [00:00<?, ?it/s]

  0%|          | 0/102 [00:00<?, ?it/s]

Processing Pairs:   0%|          | 0/102 [00:04<?, ?it/s]

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Frede\\OneDrive\\Projects and Disschaptors\\FIT_package\\results\\data\\models\\eurasian_otter_(1).joblib'

In [ ]:
# %%
import time
import os
import pandas as pd
import random
import json
from pathlib import Path
from tqdm.notebook import tqdm
from tqdm_joblib import tqdm_joblib

from FIT_python.pipeline_individual_id.pairwise_individual_id_pipeline import (
    run_all_pairwise_projections_parallel,
    generate_pairwise_comparisons_from_df
)

# %%
# --- Pfade & Daten einlesen ---
data_path = Path("C:/Users/Frede/OneDrive/Projects and Disschaptors/FIT_package/data/splits/eurasian_otter_(1)")
df = pd.read_csv(data_path / "train.csv")

# %%
# --- Feature-Spalten auswählen ---
feature_cols = [
    col for col in df.columns
    if col.startswith(("dist","ang","t")) and pd.api.types.is_numeric_dtype(df[col])
]
print(f"{len(feature_cols)} numerische Features gefunden.")

# %%
# --- Parameter definieren ---
feature_counts    = [2,5,8,10,12,14,16,18,20,30,50,100,150,200]     # k = 2…19
reducers          = ["pca","lda","umap"]
selection_methods = ["forward","random_forest"]
n_components_list = list(range(2, 6))       # Komponenten = 2…5
n_jobs            = 1 # Parallelisierung, 1 für Debugging -1 max speed


output_dir = Path("C:/Users/Frede/OneDrive/Projects and Disschaptors/FIT_package/results_long/data")
output_dir.mkdir(parents=True, exist_ok=True)

# %%
# --- Vergleiche einmal generieren & downsamplen auf 10 Pairs ---
comparisons = generate_pairwise_comparisons_from_df(
    df,
    group_sizes=[3,4,5,6,7,8],
    n_repeats=5,
    mode="both",
    selfmatch_factor=20
)
#comparisons = random.sample(comparisons, 10)
#print("Erste 3 Paare:", comparisons[:3])

# %%
all_results = []
timing_log  = []

# %%
# --- Sweep über selection_method mit Fortschrittsanzeigen ---
for sel in tqdm(selection_methods, desc="Selection methods"):
    t0 = time.time()
    # innere Bar für die Pairs
    with tqdm_joblib(tqdm(desc=f"Pairs ({sel})", total=len(comparisons))):
        results = run_all_pairwise_projections_parallel(
            comparisons=comparisons,
            df=df,
            feature_cols=feature_cols,
            k_features=feature_counts,       # komplette Liste k
            reducers=reducers,               # alle Reducer
            selection_method=sel,
            n_components=n_components_list,  # alle NCs
            debug=True,
            n_jobs=n_jobs
        )
    dur = time.time() - t0
    print(f"{sel}: {len(results)} Ergebnisse in {dur:.1f}s")
    # optional: erstes Ergebnis anschauen
    print("Sample:", results[:2])

    # In DataFrame und abspeichern
    df_res = pd.DataFrame(results)
    df_res["selection_method"] = sel
    fname = f"pairwise_{sel}_{len(comparisons)}pairs.csv"
    df_res.to_csv(output_dir / fname, index=False)

    all_results.append(df_res)
    timing_log.append({"selection_method": sel, "duration_s": dur, "n_results": len(results)})

# %%
# --- Timing & Gesamt-CSV ---
pd.DataFrame(timing_log).to_csv(output_dir / "timing_log.csv", index=False)

if all_results:
    full = pd.concat(all_results, ignore_index=True)
    full.to_csv(output_dir / "all_results_combined.csv", index=False)
    display(full.head())
else:
    print("Keine Ergebnisse zum Zusammenführen.")

In [ ]:
# nimm das erste Pair
single_pair = [comparisons[0]]

# ein einzelner Durchlauf, debug=True, n_jobs=1
res = run_all_pairwise_projections_parallel(
    comparisons     = single_pair,
    df              = df,
    feature_cols    = feature_cols,
    k_features      = [5, 10],       # z.B. nur zwei k-Werte, damit's übersichtlich bleibt
    reducers        = ["pca"],       # erstmal nur PCA
    selection_method= "forward",     # oder "random_forest"
    n_components    = [2],           # nur 2 Komponenten
    debug           = True,
    n_jobs          = 1
)

print("Result for 1 pair:", res)

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    roc_auc_score,
    balanced_accuracy_score
)
import matplotlib.pyplot as plt

# Lade kombiniertes Ergebnis
df_model = pd.read_csv(os.path.join(output_dir, "all_results_combined.csv"))

# Leere Liste für Ergebnis-Log
model_scores = []

# Iteriere über alle k-Werte
for k in sorted(df_model["k_features"].unique()):
    df_k = df_model[df_model["k_features"] == k]

    X = df_k[[
        "center_distance_ab",
        "center_distance_rcv_a",
        "center_distance_rcv_b"
    ]]
    y = df_k["same_individual"].astype(int)

    if y.nunique() < 2:
        print(f"Skipping k={k} – nur eine Klasse vorhanden.")
        continue

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42, stratify=y
    )

    clf = RandomForestClassifier(n_estimators=100, random_state=42)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    y_prob = clf.predict_proba(X_test)[:, 1]

    roc_auc = roc_auc_score(y_test, y_prob)
    bal_acc = balanced_accuracy_score(y_test, y_pred)

    print(f"\n=== k = {k} ===")
    print(classification_report(y_test, y_pred))
    print(f"ROC-AUC: {roc_auc:.3f}")
    print(f"Balanced Accuracy: {bal_acc:.3f}")

    model_scores.append({
        "k_features": k,
        "roc_auc": roc_auc,
        "balanced_accuracy": bal_acc
    })

# Zusammenfassen und plotten
scores_df = pd.DataFrame(model_scores)

plt.figure(figsize=(10, 5))
plt.plot(scores_df["k_features"], scores_df["roc_auc"], label="ROC-AUC", marker="o")
plt.plot(scores_df["k_features"], scores_df["balanced_accuracy"], label="Balanced Accuracy", marker="s")
plt.xlabel("Anzahl ausgewählter Features (k)")
plt.ylabel("Score")
plt.title("Modellperformance vs. Anzahl Features")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()